const icons = {
  "0": "weather-hurricane",
  "1": "weather-hurricane",
  "2": "weather-hurricane",
  "3": "weather-lightning-rainy",
  "4": "weather-lightning-rainy",
  "5": "weather-snowy-rainy",
  "6": "weather-snowy-rainy",
  "7": "weather-snowy-rainy",
  "8": "weather-snowy-rainy",
  "9": "weather-rainy",
  "10": "weather-snowy-rainy",
  "11": "weather-rainy",
  "12": "weather-rainy",
  "13": "weather-snowy",
  "14": "weather-snowy",
  "15": "weather-snowy",
  "16": "weather-snowy",
  "17": "weather-hail",
  "18": "weather-hail",
  "19": "weather-fog",
  "20": "weather-fog",
  "21": "weather-fog",
  "22": "weather-windy",
  "23": "weather-windy",
  "24": "weather-windy",
  "25": "weather-windy",
  "26": "weather-cloudy",
  "27": "weather-partlycloudy",
  "28": "weather-partlycloudy",
  "29": "weather-partlycloudy",
  "30": "weather-partlycloudy",
  "31": "weather-night",
  "32": "weather-sunny",
  "33": "weather-night",
  "34": "weather-sunny",
  "35": "weather-hail",
  "36": "weather-sunny",
  "37": "weather-lightning-rainy",
  "38": "weather-lightning-rainy",
  "39": "weather-lightning-rainy",
  "40": "weather-rainy",
  "41": "weather-snowy",
  "42": "weather-snowy-rainy",
  "43": "weather-snowy",
  "44": "weather-partlycloudy",
  "45": "weather-lightning-rainy",
  "46": "weather-snowy-rainy",
  "47": "weather-lightning-rainy",
  "3200": "weather-hurricane"
}

export default function getIcon(code){
  return icons[code];
}